### ISSUE TITLE
AddressInfo structure requires a deprecated `account` field to be present or produces an error otherwise

### ISSUE THREAD

**Issue by eupn** [exonum/bitcoinrpc#7]
Anchoring doesn't work and logs an error with message `Missing field 'account'` when used with bitcoind of version 0.17.

According to 0.17 documentation, field `account` in result object of `getaddressinfo` RPC method is deprecated and will be removed since version 0.18.

Temporary workaround is to run bitcoind with parameter `-deprecatedrpc=accounts`, but `account` field should be removed or made optional to be compatible with newer versions of bitcoind.

**Comment by alekseysidorov** [comment]
Yes thanks for your report.

I fixed issue by the new releases of the `bitcoinrpc` and `anchoring` crates. May you check them?
